[package]
name = "e2e-server"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
rand = "0.7.2"
log = "0.4.8"
tokio = { version = "0.2", features = ["macros"] }
e2e-grpc = { path = "../e2e-grpc" }