[package]
name = "e2e-core"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version="0.4" }
juniper-from-schema = "0.5.*"
juniper = "0.14.*"